version: "3.1"
services: 
    
    producer-app-python:
        image: py-producer:latest

    rabbitmq-one:
        image: rabbitmq:3.7-management
        environment: 
            - RABBITMQ_DEFAULT_USER=user
            - RABBITMQ_DEFAULT_PASS=password
            - RABBITMQ_ERLANG_COOKIE=SWQOKODSQALRPCLNMEQG
        ports: 
            - 15672:15672
            - 5672:5672
        volumes: 
            - $PWD/storage/rabbitmq1:/var/lib/rabbitmq

    rabbitmq-two:
        image: rabbitmq:3.7-management
        environment: 
            - RABBITMQ_DEFAULT_USER=user
            - RABBITMQ_DEFAULT_PASS=password
            - RABBITMQ_ERLANG_COOKIE=SWQOKODSQALRPCLNMEQG
        ports: 
            - 15673:15672
            - 5673:5672
        volumes: 
            - $PWD/storage/rabbitmq2:/var/lib/rabbitmq
    
    rabbitmq-three:
        image: rabbitmq:3.7-management
        environment: 
            - RABBITMQ_DEFAULT_USER=user
            - RABBITMQ_DEFAULT_PASS=password
            - RABBITMQ_ERLANG_COOKIE=SWQOKODSQALRPCLNMEQG
        ports: 
            - 15674:15672
            - 5674:5672
        volumes: 
            - $PWD/storage/rabbitmq3:/var/lib/rabbitmq
